#!/usr/bin/env bash
# Install Nginx
apt-get update
apt-get install -y nginx

# Remove default Nginx files
sudo rm -f /usr/share/nginx/html/index.html

# Configure Nginx to listen on port 80 and return "Holberton School" at the root
sudo echo "Holberton School for the win!" > /usr/share/nginx/html/index.html

# Restart Nginx without using systemctl
sudo service nginx restart
